### ISSUE TITLE
Resource state cannot be updated with WARN A managed resource "source" "login" has not been declared in the root module.

### ISSUE THREAD

**Issue by eigokor** [crossplane-contrib/provider-okta#8]
Hi, I am trying to provision Oauth app with following config

```
apiVersion: app.okta.upbound.io/v1alpha1
kind: Oauth
metadata:
  name: test-env-100-ttl4
spec:
  forProvider:
    label: "test-env-100-ttl4"
    type: "browser"
    grantTypes:
      - authorization_code
    redirectUris:
      - "https://test-env-100-ttl4.my.org.engineering/homepage/login/callback"
    postLogoutRedirectUris:
      - "https://test-env-100-ttl4.my.org.engineering/homepage/"
    loginUri: "https://est-env-100-ttl4.my.org.engineering"
    loginMode: "DISABLED"
    responseTypes:
      - code
    tokenEndpointAuthMethod: "none"
    issuerMode: "ORG_URL"
    pkceRequired: true
    autoKeyRotation: true
    consentMethod: "TRUSTED"
    clientId: dg123e4dq234gr43edq4f
 ```

On octa side application is created, below okta API GET application output:
```
{
  "id": "0oa267uti7vG4Jn0A0h8",
  "orn": null,
  "name": "oidc_client",
  "label": "test-env-100-ttl4",
  "status": "ACTIVE",
  "lastUpdated": "2024-08-23T06:45:56.000Z",
  "created": "2024-08-23T06:45:56.000Z",
  "accessibility": {
    "selfService": false,
    "errorRedirectUrl": null,
    "loginRedirectUrl": null
  },
  "visibility": {
    "autoLaunch": false,
    "autoSubmitToolbar": false,
    "hide": {
      "iOS": true,
      "web": true
    },
    "appLinks": {
      "oidc_client_link": true
    }
  },
  "features": [],
  "signOnMode": "OPENID_CONNECT",
  "credentials": {
    "userNameTemplate": {
      "template": "${source.login}",
      "type": "BUILT_IN"
    },
    "signing": {
      "kid": "RiBI46Rz2BNYbbM_ntq2pOrZk5xYyFawKgf7OVLYzXvE"
    },
    "oauthClient": {
      "autoKeyRotation": true,
      "client_id": "random",
      "token_endpoint_auth_method": "none",
      "pkce_required": true
    }
  },
  "settings": {
    "app": {},
    "notifications": {
      "vpn": {
        "network": {
          "connection": "DISABLED"
        },
        "message": null,
        "helpUrl": null
      }
    },
    "manualProvisioning": false,
    "implicitAssignment": false,
    "notes": {
      "admin": null,
      "enduser": null
    },
    "oauthClient": {
      "client_uri": null,
      "logo_uri": null,
      "redirect_uris": [
        "https://test-env-100-ttl4.my.org.engineering/homepage/login/callback"
      ],
      "post_logout_redirect_uris": [
        "https://test-env-100-ttl4.my.org.engineering/homepage/"
      ],
      "response_types": [
        "code"
      ],
      "grant_types": [
        "authorization_code"
      ],
      "initiate_login_uri": "https://test-env-100-ttl4.my.org.engineering",
      "application_type": "browser",
      "consent_method": "TRUSTED",
      "issuer_mode": "ORG_URL",
      "idp_initiated_login": {
        "mode": "DISABLED",
        "default_scope": []
      },
      "wildcard_redirect": "DISABLED",
      "dpop_bound_access_tokens": false
    }
  },
  "_links": {
    "uploadLogo": {
      "href": "https://myorg.oktapreview.com/api/v1/apps/0oa267uti7vG4Jn0A0h8/logo",
      "hints": {
        "allow": [
          "POST"
        ]
      }
    },
    "appLinks": [
      {
        "name": "oidc_client_link",
        "href": "https://myorg.oktapreview.com/home/oidc_client/0oa267uti7vG4Jn0A0h8/aln5z7uhkbM6y7bMy0g7",
        "type": "text/html"
      }
    ],
    "groups": {
      "href": "https://myorg.oktapreview.com/api/v1/apps/0oa267uti7vG4Jn0A0h8/groups"
    },
    "logo": [
      {
        "name": "medium",
        "href": "https://op1static.oktacdn.com/assets/img/logos/default.6770228fb0dab49a1695effffa5279bb.png",
        "type": "image/png"
      }
    ],
    "users": {
      "href": "https://myorg.oktapreview.com/api/v1/apps/0oa267uti7vG4Jn0A0h8/users"
    },
    "deactivate": {
      "href": "https://myorg.oktapreview.com/api/v1/apps/0oa267uti7vG4Jn0A0h8/lifecycle/deactivate"
    }
  }
}
```

but resource stuck with READY: False and SYNCED: False state
the warning message is :  observe failed: cannot run refresh: refresh failed: Reference to undeclared resource: A managed resource "source" "login" has not been declared in the root module.

```
  Warning  CannotObserveExternalResource  2m48s (x440 over 7h13m)  managed/app.okta.upbound.io/v1alpha1, kind=oauth  cannot run refresh: refresh failed: Reference to undeclared resource: A managed resource "source" "login" has not been declared in the root module.
 ```
